export type {
  Plan,
  BillingCycle,
  SubStatus,
  UserType,
  Section,
  Species,
  Sex,
  AppointmentStatus,
  AppointmentType,
  PaymentMethod,
  ProductCategory,
  DiscountType,
  SaleStatus,
  POStatus,
  GroomingStatus,
  KennelSize,
  StayStatus,
  EmailStatus,
  AuditAction,
} from "@/generated/prisma/client";
